(*
https://adventofcode.com/2020/day/7
*)

open Printf

module StrSet = Set.Make(String)

let input_test = [
    ("light red", [(1, "bright white"); (2, "muted yellow") ]);
    ("dark orange", [(3, "bright white"); (4, "muted yellow") ]);
    ("bright white", [(1, "shiny gold") ]);
    ("muted yellow", [(2, "shiny gold"); (9, "faded blue") ]);
    ("shiny gold", [(1, "dark olive"); (2, "vibrant plum") ]);
    ("dark olive", [(3, "faded blue"); (4, "dotted black") ]);
    ("vibrant plum", [(5, "faded blue"); (6, "dotted black") ]);
    ("faded blue", []);
    ("dotted black", [])
];;

let input_test2 = [
    ("shiny gold", [(2, "dark red")]);
    ("dark red", [(2, "dark orange")]);
    ("dark orange", [(2, "dark yellow")]);
    ("dark yellow", [(2, "dark green")]);
    ("dark green", [(2, "dark blue")]);
    ("dark blue", [(2, "dark violet")]);
    ("dark violet", [])
];;

let input = [
    ("vibrant salmon", [(1, "vibrant gold"); (2, "wavy aqua"); (1, "dotted crimson") ]);
    ("dotted plum", [(3, "wavy cyan") ]);
    ("muted salmon", [(2, "pale purple"); (3, "dull orange"); (2, "dotted lime"); (3, "clear crimson") ]);
    ("wavy green", [(1, "plaid crimson") ]);
    ("light salmon", [(3, "posh lime"); (1, "plaid plum"); (3, "faded yellow"); (4, "clear fuchsia") ]);
    ("dim violet", [(4, "drab tan"); (4, "drab violet"); (2, "faded coral"); (4, "dark white") ]);
    ("dim black", [(4, "posh lime") ]);
    ("drab indigo", [(4, "light aqua"); (2, "light white"); (4, "clear plum") ]);
    ("clear purple", [(4, "drab olive"); (2, "vibrant chartreuse") ]);
    ("wavy indigo", [(3, "clear maroon"); (4, "striped blue"); (2, "wavy gray"); (2, "dim magenta") ]);
    ("drab olive", [(2, "shiny salmon"); (4, "mirrored white"); (4, "mirrored fuchsia") ]);
    ("plaid crimson", [(2, "dull chartreuse"); (4, "striped maroon"); (4, "dull crimson"); (4, "plaid red") ]);
    ("pale lavender", [(4, "dotted tan"); (5, "striped olive") ]);
    ("vibrant maroon", [(2, "faded plum"); (4, "wavy aqua"); (5, "drab lavender"); (4, "light lavender") ]);
    ("wavy coral", [(5, "drab purple") ]);
    ("drab salmon", [(4, "shiny tan"); (2, "shiny white") ]);
    ("light green", [(5, "dim turquoise"); (4, "striped crimson"); (5, "dim salmon"); (3, "clear gray") ]);
    ("dark indigo", [(5, "shiny crimson") ]);
    ("dark blue", [(3, "drab indigo"); (2, "shiny beige"); (2, "shiny coral") ]);
    ("shiny cyan", [(2, "striped aqua"); (2, "drab turquoise"); (5, "light purple") ]);
    ("pale cyan", [(2, "muted violet"); (2, "clear beige"); (1, "clear indigo"); (5, "striped turquoise") ]);
    ("muted lime", [(5, "drab silver") ]);
    ("shiny brown", [(4, "clear purple"); (5, "striped chartreuse"); (5, "pale lavender") ]);
    ("muted purple", [(4, "dark purple"); (2, "dull crimson") ]);
    ("plaid turquoise", [(2, "clear gray"); (4, "clear magenta"); (4, "dull bronze") ]);
    ("clear cyan", [(3, "dotted plum"); (3, "shiny coral") ]);
    ("shiny violet", [(3, "drab chartreuse"); (1, "pale aqua"); (3, "bright aqua") ]);
    ("wavy tan", [(5, "dark magenta"); (4, "dull beige"); (1, "wavy cyan") ]);
    ("mirrored lime", [(2, "clear plum"); (3, "dark bronze"); (5, "faded turquoise"); (5, "plaid crimson") ]);
    ("wavy purple", [(3, "dark bronze"); (2, "bright bronze") ]);
    ("plaid plum", [(5, "muted tan"); (1, "drab teal"); (2, "dark purple"); (1, "dotted blue") ]);
    ("dotted cyan", [(4, "vibrant fuchsia"); (3, "muted plum") ]);
    ("striped white", [(3, "faded salmon"); (4, "plaid cyan"); (5, "wavy gray") ]);
    ("posh black", [(2, "dotted blue"); (3, "muted crimson") ]);
    ("dotted bronze", [(2, "posh tan") ]);
    ("muted gray", [(2, "posh green") ]);
    ("plaid violet", [(4, "muted orange") ]);
    ("muted green", [(3, "drab silver"); (2, "mirrored maroon"); (3, "dark teal") ]);
    ("dotted tan", [(3, "pale black") ]);
    ("dim beige", [(4, "light plum"); (4, "posh blue"); (4, "dotted purple") ]);
    ("posh magenta", [(2, "clear purple"); (4, "posh aqua") ]);
    ("bright coral", [(5, "light bronze"); (2, "vibrant crimson"); (4, "dark gold") ]);
    ("pale bronze", [(1, "striped orange") ]);
    ("dim lime", [(3, "dim green") ]);
    ("plaid green", [(2, "faded brown"); (3, "faded bronze"); (3, "pale green"); (5, "plaid magenta") ]);
    ("vibrant cyan", [(5, "pale black"); (5, "vibrant violet"); (1, "mirrored red") ]);
    ("dotted fuchsia", [(3, "dull crimson"); (2, "wavy silver"); (4, "muted purple") ]);
    ("dim red", [(2, "clear indigo"); (5, "dotted yellow") ]);
    ("faded black", [(4, "bright fuchsia") ]);
    ("faded chartreuse", [(4, "striped orange") ]);
    ("plaid blue", [(5, "dim gray"); (2, "pale salmon"); (2, "muted orange") ]);
    ("plaid teal", [(5, "bright lavender") ]);
    ("drab magenta", [(2, "dim crimson"); (1, "bright fuchsia") ]);
    ("clear violet", [(3, "mirrored white"); (5, "faded lime"); (2, "light olive"); (1, "dotted turquoise") ]);
    ("posh tan", [(3, "posh orange"); (1, "vibrant purple"); (4, "posh gray"); (2, "mirrored fuchsia") ]);
    ("posh red", [(5, "mirrored red") ]);
    ("striped lavender", [(5, "dotted crimson"); (1, "dotted purple") ]);
    ("dull salmon", [(1, "wavy black"); (2, "dull lime"); (3, "bright plum"); (2, "dark gray") ]);
    ("light tan", [(3, "wavy violet"); (1, "shiny olive"); (5, "bright brown") ]);
    ("pale orange", [(5, "vibrant orange"); (3, "wavy black") ]);
    ("mirrored green", [(1, "dark tan") ]);
    ("plaid gray", [(4, "muted magenta") ]);
    ("dim maroon", [(3, "light magenta"); (4, "dull red") ]);
    ("dull cyan", [(1, "wavy blue"); (1, "dark chartreuse") ]);
    ("mirrored blue", [(4, "dark cyan"); (4, "muted magenta"); (2, "striped olive"); (1, "posh gold") ]);
    ("plaid purple", [(1, "shiny orange"); (5, "plaid coral"); (4, "dim red"); (5, "faded aqua") ]);
    ("vibrant magenta", [(5, "posh aqua"); (5, "shiny chartreuse"); (4, "dark teal") ]);
    ("bright indigo", [(1, "dark bronze") ]);
    ("bright yellow", [(4, "muted lime"); (1, "drab maroon") ]);
    ("clear gold", [(2, "striped blue"); (3, "clear green"); (4, "drab indigo") ]);
    ("wavy red", [(5, "faded fuchsia"); (5, "mirrored indigo") ]);
    ("dark coral", [(3, "drab aqua"); (5, "bright fuchsia") ]);
    ("striped teal", [(1, "clear red"); (3, "drab magenta"); (4, "dim green"); (2, "dark fuchsia") ]);
    ("pale salmon", [(1, "muted gray"); (4, "dotted lavender"); (3, "dark maroon"); (4, "plaid plum") ]);
    ("dull plum", [(3, "dim black"); (5, "shiny aqua"); (3, "pale teal"); (4, "clear purple") ]);
    ("plaid indigo", [(4, "drab maroon"); (2, "shiny chartreuse"); (4, "shiny yellow"); (1, "pale violet") ]);
    ("shiny orange", [(5, "bright silver"); (2, "light olive"); (5, "light beige") ]);
    ("dotted salmon", [(4, "posh chartreuse"); (4, "light crimson"); (5, "muted yellow") ]);
    ("vibrant aqua", [(2, "dull brown") ]);
    ("shiny bronze", [(1, "mirrored teal"); (2, "drab tomato") ]);
    ("dark black", [(5, "muted red"); (5, "mirrored crimson") ]);
    ("muted bronze", [(3, "clear tomato"); (1, "vibrant purple") ]);
    ("faded beige", [(1, "shiny blue"); (5, "plaid lime") ]);
    ("pale green", [(2, "pale crimson"); (4, "muted cyan") ]);
    ("vibrant bronze", [(1, "bright lavender") ]);
    ("posh salmon", [(1, "clear green"); (2, "plaid yellow"); (3, "bright orange") ]);
    ("dull yellow", [(1, "clear plum"); (2, "dim bronze") ]);
    ("mirrored indigo", [(5, "dark tomato"); (5, "pale coral"); (5, "light magenta"); (5, "striped turquoise") ]);
    ("muted chartreuse", [(3, "dark tan"); (4, "dotted teal") ]);
    ("drab bronze", [(3, "pale lavender"); (1, "bright salmon"); (4, "plaid red") ]);
    ("dim cyan", [(1, "bright plum") ]);
    ("drab purple", [(1, "dim fuchsia"); (4, "mirrored turquoise"); (5, "striped blue") ]);
    ("pale violet", [(5, "posh brown"); (5, "striped plum"); (1, "dotted indigo") ]);
    ("wavy maroon", [(3, "shiny blue"); (3, "wavy cyan"); (1, "faded purple"); (4, "posh lime") ]);
    ("vibrant coral", [(3, "shiny turquoise"); (4, "mirrored maroon") ]);
    ("vibrant lavender", [(2, "drab turquoise"); (2, "clear red") ]);
    ("striped fuchsia", [(4, "dotted tan"); (4, "posh silver"); (4, "clear maroon"); (5, "wavy fuchsia") ]);
    ("muted lavender", [(2, "pale aqua"); (2, "bright green"); (5, "posh beige") ]);
    ("posh tomato", [(2, "vibrant bronze"); (3, "light brown"); (5, "posh indigo") ]);
    ("dull lavender", [(2, "wavy olive") ]);
    ("mirrored violet", [(5, "wavy violet"); (2, "posh cyan"); (2, "dull olive"); (3, "drab yellow") ]);
    ("mirrored chartreuse", [(2, "shiny salmon"); (5, "dark purple"); (2, "posh lime") ]);
    ("dim brown", [(4, "clear red"); (1, "drab blue"); (1, "pale silver"); (5, "dark gray") ]);
    ("striped magenta", [(1, "light orange"); (4, "muted beige") ]);
    ("light red", [(3, "shiny yellow"); (3, "faded tan"); (3, "vibrant lime"); (3, "muted coral") ]);
    ("muted olive", [(4, "drab coral"); (5, "light salmon"); (1, "vibrant violet") ]);
    ("clear silver", [(1, "posh aqua"); (1, "drab teal"); (4, "dark orange") ]);
    ("faded orange", [(4, "vibrant purple"); (4, "wavy cyan"); (1, "drab brown") ]);
    ("mirrored crimson", [(5, "light aqua"); (1, "wavy olive"); (2, "vibrant lime") ]);
    ("shiny plum", [(2, "shiny maroon"); (3, "dark red") ]);
    ("faded green", [(3, "striped turquoise") ]);
    ("bright orange", [(1, "dull crimson"); (1, "pale lavender"); (5, "shiny aqua") ]);
    ("dim gray", [(2, "drab indigo"); (5, "dim turquoise") ]);
    ("mirrored plum", [(1, "vibrant red"); (4, "dotted purple") ]);
    ("posh gold", [(4, "bright red") ]);
    ("posh silver", [(3, "drab coral"); (1, "faded tan"); (1, "bright silver"); (1, "shiny blue") ]);
    ("dull lime", [(5, "muted tan"); (4, "mirrored cyan") ]);
    ("faded turquoise", [(2, "pale teal"); (2, "bright green") ]);
    ("bright salmon", [(1, "dim white"); (2, "clear tomato"); (1, "bright aqua") ]);
    ("dim gold", [(3, "mirrored turquoise"); (5, "wavy tomato") ]);
    ("dull fuchsia", [(2, "pale beige"); (1, "dotted yellow") ]);
    ("dark beige", [(2, "pale magenta") ]);
    ("dotted maroon", [(2, "dark tomato"); (2, "light gray"); (3, "faded teal"); (1, "clear gray") ]);
    ("muted white", [(3, "dull turquoise"); (5, "dark bronze"); (1, "light olive"); (3, "clear bronze") ]);
    ("faded blue", [(1, "dark chartreuse"); (3, "pale aqua"); (5, "faded crimson") ]);
    ("clear aqua", [(3, "vibrant olive"); (5, "clear crimson") ]);
    ("faded cyan", [(1, "vibrant blue"); (1, "light magenta") ]);
    ("shiny aqua", [(1, "clear green") ]);
    ("bright gray", [(2, "dim fuchsia"); (1, "striped chartreuse"); (2, "clear aqua"); (2, "dull olive") ]);
    ("bright white", [(2, "light purple"); (5, "bright aqua") ]);
    ("bright lime", [(1, "pale orange"); (5, "plaid magenta"); (4, "mirrored maroon") ]);
    ("dark lavender", [(5, "mirrored bronze"); (4, "dotted aqua") ]);
    ("striped chartreuse", [(3, "striped indigo"); (2, "faded plum"); (4, "clear gray") ]);
    ("muted magenta", [(3, "clear red"); (3, "dull crimson"); (1, "clear aqua"); (4, "faded tomato") ]);
    ("clear magenta", [(2, "striped cyan"); (5, "vibrant lime"); (4, "striped salmon") ]);
    ("pale yellow", [(3, "faded fuchsia"); (2, "dotted lime"); (5, "pale gold"); (1, "plaid tomato") ]);
    ("dull teal", [(4, "dim green"); (1, "drab maroon"); (2, "dim crimson") ]);
    ("pale brown", [(5, "drab orange"); (2, "dotted purple"); (3, "plaid olive"); (3, "pale black") ]);
    ("posh blue", [(4, "faded purple"); (4, "drab turquoise") ]);
    ("pale olive", [(5, "muted silver"); (3, "mirrored plum"); (4, "vibrant lime"); (5, "striped olive") ]);
    ("plaid black", [(3, "posh yellow") ]);
    ("striped tomato", [(4, "faded blue"); (2, "shiny magenta") ]);
    ("wavy tomato", [(1, "pale gold"); (2, "dim magenta") ]);
    ("faded plum", [(3, "light violet"); (3, "posh beige"); (3, "striped aqua"); (4, "dim magenta") ]);
    ("vibrant turquoise", [(3, "muted silver"); (5, "dotted black") ]);
    ("dull white", [(5, "dim gray"); (1, "faded crimson") ]);
    ("faded purple", [(1, "vibrant orange"); (4, "pale crimson"); (5, "shiny blue"); (1, "light gold") ]);
    ("clear white", [(1, "striped orange"); (3, "pale coral"); (5, "plaid chartreuse") ]);
    ("striped maroon", [(2, "wavy olive") ]);
    ("light tomato", [(2, "pale crimson"); (3, "bright fuchsia"); (2, "pale salmon"); (3, "pale olive") ]);
    ("drab tomato", [(1, "pale olive") ]);
    ("dark aqua", [(1, "shiny magenta"); (4, "faded lime"); (4, "faded gold") ]);
    ("plaid bronze", [(2, "pale purple") ]);
    ("dark plum", [(3, "wavy brown"); (1, "bright salmon") ]);
    ("dark purple", [(4, "dotted red") ]);
    ("light teal", [(1, "vibrant indigo"); (5, "wavy olive"); (4, "clear maroon"); (1, "light silver") ]);
    ("drab fuchsia", [(3, "faded turquoise"); (5, "dim yellow") ]);
    ("light turquoise", [(1, "dotted blue"); (4, "mirrored tomato") ]);
    ("clear maroon", [(4, "mirrored green") ]);
    ("posh maroon", [(3, "dim black"); (3, "bright gold"); (3, "mirrored white"); (1, "clear lavender") ]);
    ("dotted blue", [(2, "wavy maroon") ]);
    ("bright tan", [(4, "faded turquoise"); (5, "drab coral"); (5, "dull red"); (2, "dim gray") ]);
    ("dark salmon", [(4, "clear fuchsia"); (5, "mirrored red") ]);
    ("mirrored fuchsia", [(4, "bright tomato"); (3, "vibrant orange") ]);
    ("vibrant green", [(1, "clear lavender") ]);
    ("dim white", [(5, "dull red") ]);
    ("light white", [(3, "dark purple"); (1, "mirrored fuchsia"); (1, "plaid gold"); (1, "posh lime") ]);
    ("dark turquoise", [(3, "striped green"); (1, "dull gold"); (2, "pale gray") ]);
    ("light purple", [(5, "muted brown"); (5, "muted purple"); (4, "dull yellow"); (5, "vibrant gold") ]);
    ("posh lavender", [(5, "posh yellow"); (4, "plaid plum"); (1, "dark fuchsia"); (1, "bright maroon") ]);
    ("posh crimson", [(1, "vibrant gold"); (5, "clear green"); (2, "posh chartreuse") ]);
    ("wavy lime", [(5, "mirrored beige") ]);
    ("wavy black", [(1, "plaid orange"); (4, "shiny green"); (3, "shiny blue"); (4, "muted red") ]);
    ("muted red", [(4, "vibrant lime"); (2, "drab black"); (4, "vibrant red"); (5, "faded beige") ]);
    ("vibrant gold", [(2, "bright silver"); (4, "faded teal"); (2, "vibrant orange"); (3, "striped salmon") ]);
    ("shiny crimson", [(2, "bright yellow") ]);
    ("muted turquoise", [(5, "bright plum") ]);
    ("posh orange", [(4, "vibrant yellow"); (5, "clear crimson") ]);
    ("wavy aqua", [(5, "shiny green"); (5, "bright fuchsia"); (4, "muted fuchsia") ]);
    ("clear green", [(4, "dotted plum"); (2, "vibrant olive"); (5, "pale beige") ]);
    ("pale aqua", [(3, "dark tomato"); (5, "posh lime") ]);
    ("drab maroon", [(5, "bright magenta"); (2, "bright plum"); (5, "clear green"); (3, "faded tomato") ]);
    ("vibrant plum", [(3, "light crimson"); (5, "dotted silver"); (5, "mirrored red"); (1, "dotted turquoise") ]);
    ("posh yellow", [(5, "plaid lavender"); (5, "dim tomato") ]);
    ("faded brown", [(1, "striped orange"); (5, "wavy green") ]);
    ("drab cyan", [(4, "faded teal"); (3, "vibrant aqua"); (2, "light chartreuse"); (3, "dark orange") ]);
    ("dark lime", [(4, "vibrant blue") ]);
    ("faded coral", [(4, "wavy green"); (4, "mirrored gold"); (3, "striped fuchsia"); (1, "pale fuchsia") ]);
    ("dark orange", [(1, "dotted red"); (2, "vibrant red") ]);
    ("wavy magenta", [(3, "dull chartreuse"); (2, "dim maroon"); (2, "clear maroon") ]);
    ("plaid coral", [(4, "drab tan"); (1, "pale tan") ]);
    ("mirrored salmon", [(1, "muted bronze"); (5, "muted purple") ]);
    ("dim tomato", [(2, "drab silver"); (4, "mirrored purple"); (1, "dull olive"); (5, "dotted purple") ]);
    ("wavy gold", [(3, "dark crimson"); (1, "dim white") ]);
    ("light fuchsia", [(3, "mirrored green"); (2, "wavy fuchsia") ]);
    ("pale tomato", [(4, "clear purple"); (5, "faded brown"); (4, "light coral") ]);
    ("faded yellow", [(5, "wavy olive"); (2, "pale lavender"); (4, "bright plum") ]);
    ("light violet", [(1, "dotted red"); (4, "dim aqua") ]);
    ("posh lime", [(2, "pale crimson"); (1, "pale gold"); (1, "shiny blue"); (4, "muted gray") ]);
    ("mirrored silver", [(4, "striped bronze"); (3, "faded salmon"); (3, "drab green"); (4, "striped green") ]);
    ("dark green", [(5, "striped maroon"); (3, "dim olive"); (4, "vibrant chartreuse"); (5, "dim white") ]);
    ("mirrored olive", [(2, "dotted red"); (5, "dim white") ]);
    ("dark teal", [(3, "wavy olive"); (3, "pale crimson") ]);
    ("pale tan", [(2, "dark orange"); (5, "bright plum"); (4, "pale crimson") ]);
    ("wavy plum", [(3, "dull lime") ]);
    ("light indigo", [(5, "dark magenta") ]);
    ("drab lime", [(1, "bright fuchsia"); (4, "wavy brown") ]);
    ("drab tan", [(3, "bright tomato"); (1, "muted green") ]);
    ("vibrant indigo", [(5, "dull chartreuse"); (5, "clear aqua") ]);
    ("dark bronze", [(3, "dull red"); (3, "mirrored maroon"); (1, "muted green") ]);
    ("shiny red", [(2, "dark bronze"); (4, "faded magenta"); (5, "dull teal") ]);
    ("shiny black", [(3, "vibrant olive"); (2, "plaid lime"); (5, "shiny gold"); (2, "dotted plum") ]);
    ("light gold", [(5, "vibrant olive") ]);
    ("light plum", [(5, "clear gray"); (5, "dotted chartreuse"); (4, "plaid red"); (1, "plaid lime") ]);
    ("bright violet", [(4, "bright maroon"); (5, "posh red"); (2, "faded olive"); (4, "dim gray") ]);
    ("faded red", [(4, "drab maroon"); (4, "vibrant violet"); (1, "faded purple"); (2, "dotted black") ]);
    ("muted orange", [(4, "plaid chartreuse"); (5, "muted lavender"); (2, "faded purple") ]);
    ("clear coral", [(2, "drab teal"); (5, "bright turquoise") ]);
    ("wavy orange", [(4, "muted cyan"); (3, "light indigo"); (5, "bright black"); (5, "light salmon") ]);
    ("faded fuchsia", [(3, "pale gold"); (3, "faded salmon"); (4, "pale red") ]);
    ("light brown", [(4, "pale silver"); (4, "clear tan") ]);
    ("shiny gray", [(3, "muted teal"); (1, "bright purple"); (2, "bright olive"); (4, "mirrored green") ]);
    ("bright brown", [(2, "dark teal"); (5, "light plum"); (2, "plaid olive"); (5, "dark chartreuse") ]);
    ("mirrored white", [(1, "wavy gray"); (3, "bright tomato"); (1, "muted silver"); (4, "striped olive") ]);
    ("pale magenta", [(1, "clear gray"); (1, "muted gray"); (1, "wavy cyan"); (4, "dull brown") ]);
    ("bright magenta", [(2, "muted tan"); (1, "pale gold"); (2, "wavy cyan"); (4, "vibrant orange") ]);
    ("clear teal", [(1, "dark teal"); (2, "vibrant lime") ]);
    ("light orange", [(3, "light gold"); (4, "clear plum"); (4, "dotted indigo") ]);
    ("plaid cyan", [(1, "pale magenta") ]);
    ("wavy chartreuse", [(2, "posh green"); (5, "dotted purple"); (2, "dark tomato"); (3, "muted gray") ]);
    ("light coral", [(5, "clear gray"); (2, "posh purple"); (2, "mirrored violet") ]);
    ("dull violet", [(3, "dotted blue"); (5, "mirrored tomato"); (1, "dull chartreuse"); (2, "posh beige") ]);
    ("bright tomato", [(3, "vibrant red"); (3, "muted gray") ]);
    ("mirrored magenta", [(4, "wavy brown") ]);
    ("muted indigo", [(4, "wavy chartreuse"); (3, "vibrant indigo"); (2, "posh magenta"); (1, "plaid crimson") ]);
    ("bright maroon", [(2, "dull violet"); (2, "faded tan"); (3, "striped gray"); (5, "pale magenta") ]);
    ("dark tomato", []);
    ("pale fuchsia", [(3, "drab silver"); (4, "faded purple"); (2, "mirrored cyan"); (5, "dark bronze") ]);
    ("dull black", [(1, "dull indigo"); (1, "wavy brown"); (5, "striped gray") ]);
    ("pale white", [(3, "light gray"); (2, "plaid lavender"); (1, "wavy maroon") ]);
    ("shiny turquoise", [(4, "pale red") ]);
    ("drab brown", [(5, "mirrored plum"); (4, "dotted red") ]);
    ("bright green", [(1, "dull lime"); (2, "clear lavender") ]);
    ("wavy blue", [(4, "dotted purple") ]);
    ("muted aqua", [(5, "faded plum"); (3, "plaid plum"); (4, "dotted tan"); (1, "clear gray") ]);
    ("clear yellow", [(4, "dotted indigo"); (3, "vibrant aqua"); (4, "vibrant orange") ]);
    ("mirrored gray", [(4, "shiny crimson"); (2, "mirrored coral"); (1, "dotted tan"); (4, "posh cyan") ]);
    ("dark maroon", [(1, "dark salmon"); (3, "muted coral") ]);
    ("posh plum", [(1, "mirrored bronze"); (4, "plaid purple"); (3, "vibrant white") ]);
    ("bright teal", [(2, "pale aqua"); (1, "mirrored black") ]);
    ("wavy teal", [(5, "plaid tan"); (3, "dull black"); (1, "bright teal"); (3, "clear teal") ]);
    ("dotted magenta", [(1, "plaid plum"); (5, "plaid salmon"); (3, "light gold") ]);
    ("faded tomato", [(1, "dark bronze"); (2, "faded purple"); (4, "vibrant red"); (4, "pale lavender") ]);
    ("dull blue", [(3, "dotted bronze"); (2, "shiny olive"); (3, "muted gold") ]);
    ("posh aqua", [(5, "vibrant orange"); (1, "vibrant olive") ]);
    ("mirrored black", [(3, "dark teal"); (4, "plaid chartreuse"); (2, "light salmon"); (2, "vibrant white") ]);
    ("wavy violet", [(5, "vibrant indigo") ]);
    ("vibrant blue", [(4, "shiny olive"); (4, "light olive"); (2, "muted green") ]);
    ("dotted green", [(3, "shiny violet"); (3, "posh black"); (3, "dark lime") ]);
    ("wavy cyan", [(2, "muted gray"); (3, "vibrant olive"); (4, "striped olive"); (4, "drab silver") ]);
    ("faded maroon", [(5, "bright yellow"); (2, "bright tomato"); (5, "mirrored magenta") ]);
    ("dull olive", [(1, "bright plum"); (2, "pale crimson") ]);
    ("clear lime", [(5, "striped blue"); (5, "wavy blue"); (3, "drab tan"); (1, "shiny olive") ]);
    ("striped yellow", [(1, "mirrored red") ]);
    ("plaid magenta", [(2, "clear yellow"); (1, "pale coral"); (3, "muted bronze") ]);
    ("light lime", [(1, "dim turquoise") ]);
    ("striped brown", [(3, "mirrored brown"); (4, "clear cyan"); (5, "bright white"); (1, "muted maroon") ]);
    ("dotted indigo", [(3, "light olive"); (1, "dull chartreuse") ]);
    ("shiny tan", [(2, "dull lime"); (5, "shiny black"); (5, "dull teal") ]);
    ("clear olive", [(5, "drab coral"); (4, "striped aqua"); (4, "dotted lavender") ]);
    ("plaid chartreuse", [(1, "plaid red"); (4, "faded tomato") ]);
    ("dotted olive", [(2, "dull yellow") ]);
    ("faded lime", [(5, "dotted aqua"); (4, "shiny silver"); (4, "muted white") ]);
    ("vibrant silver", [(4, "dotted teal"); (3, "posh olive") ]);
    ("striped beige", [(2, "vibrant white"); (3, "dark gold"); (4, "posh violet"); (4, "bright chartreuse") ]);
    ("dim plum", [(2, "striped indigo"); (2, "vibrant gold") ]);
    ("clear crimson", [(5, "vibrant red") ]);
    ("plaid maroon", [(4, "clear crimson") ]);
    ("drab coral", [(2, "plaid plum") ]);
    ("dull bronze", [(4, "pale black"); (1, "dull tan"); (5, "dull cyan"); (4, "pale lavender") ]);
    ("wavy bronze", [(4, "posh coral"); (2, "bright silver") ]);
    ("dull aqua", [(3, "dotted orange"); (3, "pale teal") ]);
    ("muted plum", [(1, "light blue"); (2, "muted maroon"); (4, "dull olive") ]);
    ("vibrant tan", [(4, "drab teal") ]);
    ("dull tomato", [(5, "dull white") ]);
    ("muted yellow", [(3, "dark yellow"); (5, "faded beige") ]);
    ("shiny white", [(4, "bright silver") ]);
    ("muted crimson", [(1, "clear maroon") ]);
    ("muted violet", [(3, "dotted yellow"); (1, "light indigo"); (4, "mirrored black"); (5, "drab lime") ]);
    ("posh white", [(3, "faded brown"); (2, "dull yellow") ]);
    ("wavy crimson", [(3, "shiny black"); (2, "dotted blue"); (4, "dark maroon") ]);
    ("clear salmon", [(1, "mirrored magenta"); (4, "bright chartreuse"); (5, "vibrant black"); (2, "vibrant chartreuse") ]);
    ("pale teal", [(5, "mirrored white"); (2, "plaid orange"); (4, "muted lime") ]);
    ("light aqua", [(2, "shiny salmon"); (3, "dark tomato"); (1, "mirrored purple") ]);
    ("clear beige", [(1, "muted crimson") ]);
    ("vibrant olive", [(5, "dark tomato"); (1, "pale gold"); (4, "muted tan") ]);
    ("plaid brown", [(3, "mirrored lavender"); (1, "muted crimson"); (3, "muted green"); (1, "bright lavender") ]);
    ("dim magenta", [(4, "pale fuchsia"); (3, "drab black"); (4, "plaid orange") ]);
    ("bright purple", [(3, "muted gray"); (3, "pale coral") ]);
    ("posh indigo", [(2, "bright beige"); (2, "dim tomato") ]);
    ("drab lavender", [(2, "dotted chartreuse"); (1, "posh green"); (3, "light silver"); (1, "dotted black") ]);
    ("pale crimson", []);
    ("posh gray", [(1, "muted green") ]);
    ("shiny lime", [(3, "mirrored maroon"); (1, "posh crimson"); (4, "mirrored orange"); (2, "posh olive") ]);
    ("muted beige", [(1, "posh tan"); (3, "posh olive"); (1, "faded white"); (2, "posh green") ]);
    ("light black", [(3, "striped green"); (2, "pale salmon"); (3, "muted crimson") ]);
    ("dark gold", [(5, "striped maroon"); (2, "pale fuchsia"); (3, "light gold") ]);
    ("light bronze", [(2, "clear purple"); (4, "dim crimson") ]);
    ("muted blue", [(1, "faded gray"); (4, "muted salmon"); (5, "dull bronze") ]);
    ("vibrant orange", []);
    ("dim lavender", [(1, "vibrant indigo") ]);
    ("posh fuchsia", [(3, "clear fuchsia"); (2, "shiny green"); (3, "plaid plum") ]);
    ("dim tan", [(5, "pale plum"); (3, "posh gray"); (1, "clear yellow") ]);
    ("pale lime", []);
    ("striped blue", [(5, "pale black") ]);
    ("shiny tomato", [(1, "dim fuchsia"); (5, "faded blue"); (3, "muted brown"); (3, "mirrored salmon") ]);
    ("dotted orange", [(4, "bright tomato"); (1, "light silver") ]);
    ("muted tan", []);
    ("pale black", [(2, "dull brown"); (4, "mirrored chartreuse"); (2, "dim aqua") ]);
    ("shiny purple", [(3, "dotted indigo"); (5, "vibrant gold"); (2, "light chartreuse"); (4, "clear magenta") ]);
    ("dull brown", [(2, "bright beige"); (4, "vibrant orange"); (2, "bright tomato"); (4, "clear lavender") ]);
    ("plaid aqua", [(3, "plaid indigo") ]);
    ("dark olive", [(1, "pale plum"); (4, "dim maroon") ]);
    ("dark silver", [(3, "shiny blue"); (2, "muted gray"); (4, "drab coral") ]);
    ("clear turquoise", [(5, "light violet"); (3, "drab yellow") ]);
    ("wavy brown", [(3, "shiny coral"); (3, "shiny salmon"); (1, "drab magenta") ]);
    ("dim indigo", [(5, "bright green") ]);
    ("mirrored gold", [(1, "plaid magenta"); (2, "plaid gold"); (4, "light turquoise") ]);
    ("drab red", [(3, "mirrored bronze") ]);
    ("faded bronze", [(1, "vibrant aqua"); (2, "clear tomato"); (2, "dull tan") ]);
    ("bright lavender", [(4, "drab coral"); (1, "bright green") ]);
    ("wavy lavender", [(2, "wavy green"); (4, "drab silver"); (5, "light turquoise") ]);
    ("wavy salmon", [(2, "dotted gray"); (4, "bright chartreuse"); (4, "striped gray") ]);
    ("dotted yellow", [(4, "dark salmon"); (1, "posh tan"); (4, "drab tomato"); (4, "vibrant chartreuse") ]);
    ("dull turquoise", [(5, "drab silver"); (1, "dark orange") ]);
    ("pale gray", [(4, "dull aqua"); (4, "faded gold"); (2, "mirrored orange"); (2, "dim magenta") ]);
    ("dark red", [(2, "bright gray"); (4, "bright black") ]);
    ("dim fuchsia", [(3, "bright magenta"); (5, "pale crimson") ]);
    ("vibrant lime", [(2, "wavy maroon"); (2, "pale magenta"); (4, "pale crimson"); (3, "drab orange") ]);
    ("bright bronze", [(4, "vibrant black"); (3, "drab fuchsia"); (3, "striped cyan"); (3, "dotted blue") ]);
    ("muted coral", [(3, "wavy white"); (1, "plaid tan") ]);
    ("wavy white", [(2, "drab maroon") ]);
    ("pale coral", [(3, "dotted bronze"); (1, "dull gold") ]);
    ("drab white", [(3, "drab silver"); (3, "bright tomato"); (1, "bright silver") ]);
    ("light olive", [(3, "muted tan"); (2, "mirrored tomato") ]);
    ("mirrored tomato", [(2, "dark tomato"); (3, "shiny gold") ]);
    ("light crimson", [(4, "clear magenta"); (2, "plaid coral"); (5, "dull chartreuse"); (5, "dark teal") ]);
    ("bright cyan", [(1, "clear chartreuse"); (1, "striped brown"); (5, "light tomato"); (4, "dark coral") ]);
    ("vibrant fuchsia", [(3, "dull white"); (1, "dim purple"); (5, "shiny yellow") ]);
    ("drab gold", [(5, "wavy chartreuse") ]);
    ("plaid yellow", [(4, "faded plum"); (1, "faded indigo"); (2, "drab purple"); (1, "light purple") ]);
    ("bright black", [(2, "clear yellow"); (1, "dotted red"); (4, "dim white") ]);
    ("pale maroon", [(2, "vibrant tomato"); (3, "mirrored tomato") ]);
    ("wavy gray", [(2, "wavy cyan"); (2, "dark tomato"); (4, "vibrant orange"); (5, "pale silver") ]);
    ("faded salmon", [(4, "bright plum") ]);
    ("shiny teal", [(4, "dark magenta") ]);
    ("dim bronze", [(5, "striped olive"); (5, "dotted plum"); (4, "dark purple") ]);
    ("dotted lavender", [(4, "striped indigo"); (2, "mirrored red"); (2, "bright chartreuse"); (4, "bright teal") ]);
    ("plaid beige", [(4, "vibrant green"); (3, "striped violet"); (5, "vibrant blue") ]);
    ("dull purple", [(1, "dark beige"); (1, "drab silver"); (4, "faded fuchsia"); (2, "vibrant olive") ]);
    ("bright olive", [(3, "faded salmon"); (1, "wavy magenta"); (5, "dim yellow") ]);
    ("mirrored maroon", [(3, "bright magenta"); (5, "pale lime"); (3, "striped olive") ]);
    ("clear brown", [(2, "mirrored orange"); (5, "bright cyan") ]);
    ("drab teal", [(3, "dull olive") ]);
    ("clear red", [(1, "bright maroon") ]);
    ("vibrant black", [(4, "pale fuchsia"); (3, "clear lavender"); (2, "shiny blue"); (3, "dotted blue") ]);
    ("faded white", [(3, "wavy coral"); (4, "faded yellow"); (5, "shiny olive"); (1, "plaid orange") ]);
    ("dotted aqua", [(1, "wavy white"); (3, "dotted blue"); (5, "pale lavender"); (4, "clear aqua") ]);
    ("pale blue", [(3, "dim salmon"); (3, "muted cyan"); (5, "pale fuchsia") ]);
    ("dim turquoise", [(4, "vibrant chartreuse"); (2, "dark silver"); (3, "pale gold") ]);
    ("dull magenta", [(3, "muted salmon"); (4, "dotted gray"); (3, "light salmon") ]);
    ("dotted coral", [(2, "mirrored tomato"); (1, "vibrant teal"); (3, "dull crimson") ]);
    ("dull beige", [(2, "faded fuchsia") ]);
    ("shiny gold", [(4, "bright beige"); (3, "dull crimson"); (4, "mirrored maroon"); (3, "bright tomato") ]);
    ("pale indigo", [(2, "dotted teal"); (3, "faded teal"); (4, "wavy indigo") ]);
    ("shiny magenta", [(5, "bright tomato"); (5, "dull lime"); (5, "mirrored bronze"); (2, "dim black") ]);
    ("muted cyan", [(2, "dark bronze"); (5, "drab silver"); (4, "dotted chartreuse") ]);
    ("plaid orange", [(4, "light plum"); (5, "shiny salmon"); (5, "posh beige") ]);
    ("shiny green", [(5, "dotted tan"); (5, "mirrored olive"); (1, "dark teal") ]);
    ("dull maroon", [(1, "striped black"); (4, "clear green") ]);
    ("drab aqua", [(1, "striped indigo"); (3, "vibrant white") ]);
    ("bright gold", [(4, "mirrored beige"); (4, "mirrored yellow") ]);
    ("plaid tan", [(5, "shiny aqua") ]);
    ("striped plum", [(4, "clear magenta"); (2, "dark gold") ]);
    ("vibrant teal", [(1, "dim aqua"); (4, "vibrant violet"); (3, "plaid olive"); (1, "mirrored olive") ]);
    ("posh bronze", [(5, "dark tomato"); (5, "shiny silver") ]);
    ("dim orange", [(4, "dull salmon") ]);
    ("striped indigo", [(4, "drab magenta") ]);
    ("vibrant yellow", [(4, "drab olive"); (4, "wavy olive"); (2, "dark teal"); (2, "faded purple") ]);
    ("striped purple", [(5, "pale red") ]);
    ("dim coral", [(1, "plaid maroon"); (2, "pale magenta"); (1, "pale indigo"); (2, "dotted turquoise") ]);
    ("muted silver", [(4, "mirrored turquoise") ]);
    ("posh cyan", [(3, "dotted purple") ]);
    ("plaid lavender", [(3, "muted gray"); (1, "light plum") ]);
    ("faded tan", [(1, "mirrored cyan"); (2, "plaid crimson"); (5, "mirrored maroon") ]);
    ("clear lavender", [(4, "pale gold"); (1, "posh lime"); (4, "pale crimson") ]);
    ("dull gray", [(5, "shiny crimson"); (5, "wavy cyan"); (3, "posh lavender") ]);
    ("dull green", [(1, "faded bronze"); (3, "vibrant indigo"); (2, "muted fuchsia"); (4, "dotted silver") ]);
    ("dark magenta", [(3, "wavy white"); (3, "plaid plum"); (4, "wavy lavender"); (3, "drab magenta") ]);
    ("plaid red", [(1, "bright turquoise") ]);
    ("dull coral", [(4, "clear tomato") ]);
    ("posh turquoise", [(5, "dull gold"); (4, "mirrored chartreuse") ]);
    ("drab crimson", [(2, "dull tomato"); (5, "posh orange"); (5, "shiny violet") ]);
    ("clear tan", [(1, "pale fuchsia"); (4, "light aqua"); (3, "shiny blue"); (3, "bright turquoise") ]);
    ("dotted brown", [(4, "drab magenta"); (5, "plaid crimson"); (2, "posh beige") ]);
    ("light silver", [(3, "mirrored green"); (5, "mirrored maroon"); (5, "shiny blue") ]);
    ("dotted gold", [(2, "dim magenta") ]);
    ("drab yellow", [(5, "pale purple") ]);
    ("faded lavender", [(5, "muted cyan") ]);
    ("vibrant beige", [(4, "clear turquoise"); (2, "dark fuchsia"); (1, "pale gray"); (5, "dim beige") ]);
    ("clear fuchsia", [(1, "pale fuchsia"); (1, "wavy turquoise"); (5, "faded gray") ]);
    ("shiny chartreuse", [(4, "vibrant green"); (1, "dotted teal") ]);
    ("dim purple", [(1, "bright turquoise") ]);
    ("clear indigo", [(4, "light white"); (3, "vibrant orange") ]);
    ("wavy turquoise", [(5, "bright magenta") ]);
    ("vibrant chartreuse", [(4, "mirrored chartreuse"); (2, "muted tan"); (2, "plaid lime"); (3, "striped olive") ]);
    ("dark chartreuse", [(5, "shiny blue") ]);
    ("clear plum", [(3, "pale lime") ]);
    ("dotted tomato", [(5, "bright red"); (2, "bright olive"); (5, "drab silver"); (4, "clear magenta") ]);
    ("mirrored beige", [(4, "light violet"); (5, "mirrored salmon"); (4, "dim yellow"); (5, "bright yellow") ]);
    ("posh teal", [(2, "plaid turquoise"); (3, "pale salmon"); (1, "striped plum") ]);
    ("dull chartreuse", [(5, "pale lavender"); (1, "bright turquoise"); (3, "pale beige") ]);
    ("mirrored lavender", [(4, "vibrant tomato"); (2, "plaid tan"); (5, "bright magenta") ]);
    ("dark gray", [(5, "wavy turquoise"); (4, "wavy gray"); (4, "dark bronze"); (4, "pale aqua") ]);
    ("dark white", [(4, "clear maroon"); (2, "vibrant olive"); (1, "dull lime"); (1, "faded lime") ]);
    ("dull indigo", [(4, "clear fuchsia"); (3, "dotted tan"); (1, "plaid cyan") ]);
    ("striped tan", [(3, "pale brown") ]);
    ("dull gold", [(2, "dark yellow"); (3, "dull olive") ]);
    ("light lavender", [(2, "plaid red"); (5, "dotted purple"); (1, "bright beige"); (3, "pale beige") ]);
    ("faded teal", [(4, "mirrored olive") ]);
    ("plaid salmon", [(1, "dark bronze"); (5, "pale yellow"); (1, "striped cyan"); (2, "muted cyan") ]);
    ("dotted purple", [(1, "bright turquoise"); (1, "posh green") ]);
    ("dull silver", [(3, "striped salmon"); (4, "posh violet"); (4, "striped orange") ]);
    ("drab chartreuse", [(4, "pale lavender") ]);
    ("striped coral", [(5, "bright gray"); (4, "dark teal"); (5, "dotted purple") ]);
    ("wavy olive", []);
    ("plaid olive", [(1, "pale black"); (3, "clear plum") ]);
    ("drab black", [(3, "striped olive"); (2, "mirrored chartreuse"); (5, "pale silver") ]);
    ("striped lime", [(3, "dark chartreuse"); (5, "pale silver"); (2, "plaid crimson"); (4, "clear fuchsia") ]);
    ("drab beige", [(4, "dim black"); (4, "striped black"); (4, "dull crimson"); (5, "dark gray") ]);
    ("muted tomato", [(3, "light bronze"); (3, "pale salmon"); (2, "vibrant chartreuse") ]);
    ("bright fuchsia", [(5, "drab orange"); (3, "pale black"); (3, "mirrored white"); (5, "faded tomato") ]);
    ("vibrant gray", [(4, "posh lime"); (2, "dark purple"); (4, "clear aqua") ]);
    ("shiny yellow", [(5, "bright beige"); (2, "vibrant red"); (5, "dim yellow"); (2, "vibrant yellow") ]);
    ("posh coral", [(5, "drab indigo") ]);
    ("muted fuchsia", [(5, "shiny silver"); (2, "dotted salmon"); (1, "muted tan") ]);
    ("muted brown", [(4, "clear maroon"); (5, "dim purple"); (4, "wavy maroon"); (2, "muted red") ]);
    ("posh chartreuse", [(5, "muted tan"); (3, "drab teal") ]);
    ("vibrant brown", [(1, "wavy bronze"); (5, "bright red"); (4, "muted fuchsia"); (4, "clear fuchsia") ]);
    ("posh purple", [(2, "drab turquoise"); (5, "striped blue"); (1, "muted cyan") ]);
    ("plaid lime", [(3, "muted gray"); (5, "vibrant red"); (1, "wavy gray"); (1, "pale silver") ]);
    ("posh violet", [(2, "faded crimson"); (1, "shiny olive"); (3, "bright magenta"); (1, "drab silver") ]);
    ("striped gold", [(5, "faded salmon"); (2, "drab bronze"); (2, "dark plum") ]);
    ("striped gray", [(2, "mirrored crimson"); (5, "faded beige"); (1, "dull red") ]);
    ("dim blue", [(2, "dark coral"); (3, "dim yellow"); (1, "dull salmon") ]);
    ("bright silver", [(2, "mirrored tomato"); (3, "bright plum"); (4, "pale lavender"); (1, "clear tomato") ]);
    ("striped red", [(4, "light yellow"); (5, "mirrored white"); (5, "plaid gold") ]);
    ("shiny maroon", [(3, "wavy cyan"); (1, "mirrored tomato"); (1, "mirrored coral") ]);
    ("mirrored brown", [(2, "mirrored olive"); (3, "mirrored green"); (1, "dim tomato") ]);
    ("striped olive", []);
    ("striped violet", [(5, "bright tomato") ]);
    ("mirrored aqua", [(4, "dark gray"); (5, "shiny blue"); (2, "pale silver") ]);
    ("plaid white", [(3, "dim maroon"); (2, "dim tan") ]);
    ("drab orange", [(5, "striped olive") ]);
    ("dark brown", [(2, "mirrored bronze"); (5, "clear maroon"); (2, "dull lime") ]);
    ("dotted silver", [(1, "dark gold"); (1, "drab black"); (3, "pale aqua") ]);
    ("pale plum", [(5, "striped maroon"); (5, "dotted purple"); (4, "shiny magenta") ]);
    ("faded indigo", [(1, "posh cyan"); (5, "bright green") ]);
    ("mirrored teal", [(3, "muted indigo"); (4, "clear fuchsia"); (4, "vibrant teal"); (5, "drab violet") ]);
    ("shiny lavender", [(5, "striped beige"); (2, "dull magenta"); (4, "clear tan") ]);
    ("pale beige", [(5, "mirrored maroon") ]);
    ("striped bronze", [(1, "pale orange"); (5, "shiny cyan"); (5, "plaid purple"); (1, "vibrant chartreuse") ]);
    ("faded gold", [(3, "pale brown"); (2, "dull violet"); (2, "clear maroon"); (4, "dull lime") ]);
    ("clear tomato", [(4, "vibrant orange"); (3, "bright tomato"); (3, "wavy chartreuse"); (5, "wavy olive") ]);
    ("pale red", [(5, "wavy blue"); (5, "dark purple"); (1, "bright tomato"); (4, "dark tan") ]);
    ("vibrant red", [(5, "wavy gray"); (5, "dark tomato") ]);
    ("dim salmon", [(2, "faded crimson") ]);
    ("shiny blue", [(4, "muted tan"); (2, "vibrant orange") ]);
    ("vibrant white", [(3, "mirrored cyan") ]);
    ("dark violet", [(5, "vibrant blue"); (3, "wavy tomato") ]);
    ("pale gold", []);
    ("dim silver", [(4, "drab tan"); (4, "pale silver"); (5, "clear bronze"); (4, "drab maroon") ]);
    ("drab blue", [(5, "vibrant indigo"); (3, "muted turquoise") ]);
    ("drab plum", [(2, "dim turquoise"); (2, "drab violet"); (1, "light gray"); (3, "clear tan") ]);
    ("bright plum", [(3, "wavy olive") ]);
    ("dark fuchsia", [(4, "dotted indigo"); (3, "dark brown"); (1, "clear white") ]);
    ("bright turquoise", [(1, "posh lime"); (2, "wavy olive"); (1, "pale crimson") ]);
    ("dotted turquoise", [(3, "faded plum"); (1, "bright tomato") ]);
    ("shiny indigo", [(1, "wavy chartreuse") ]);
    ("dark yellow", [(2, "light gold") ]);
    ("posh olive", [(2, "shiny indigo") ]);
    ("light chartreuse", [(5, "drab turquoise"); (2, "faded purple"); (3, "faded gray") ]);
    ("vibrant tomato", [(3, "light olive"); (4, "shiny purple") ]);
    ("posh brown", [(4, "shiny green"); (1, "pale purple") ]);
    ("bright chartreuse", [(3, "light gold") ]);
    ("dotted lime", [(5, "wavy cyan") ]);
    ("drab violet", [(4, "dark beige"); (1, "plaid gold"); (3, "faded beige") ]);
    ("drab green", [(4, "dotted bronze"); (5, "clear silver"); (4, "faded salmon") ]);
    ("wavy beige", [(2, "clear cyan"); (2, "dim tomato") ]);
    ("wavy yellow", [(4, "pale green"); (3, "mirrored green"); (5, "faded brown"); (1, "clear orange") ]);
    ("plaid tomato", [(3, "dull yellow"); (2, "faded blue"); (1, "dull teal") ]);
    ("dull red", [(4, "posh green"); (1, "shiny salmon"); (2, "bright tomato"); (4, "vibrant red") ]);
    ("striped salmon", [(4, "dim bronze"); (4, "light gold"); (3, "posh beige") ]);
    ("dim crimson", [(1, "dull crimson"); (4, "drab silver") ]);
    ("plaid silver", [(3, "dull black"); (5, "shiny silver"); (4, "dark beige"); (2, "clear aqua") ]);
    ("clear bronze", [(1, "drab coral"); (2, "vibrant red") ]);
    ("dotted gray", [(1, "plaid plum"); (2, "dotted purple"); (5, "striped violet"); (3, "bright tomato") ]);
    ("striped silver", [(2, "plaid coral"); (5, "bright orange"); (1, "pale brown") ]);
    ("shiny beige", [(4, "dim turquoise") ]);
    ("posh green", []);
    ("plaid gold", [(3, "pale fuchsia"); (5, "dull lime"); (5, "wavy chartreuse"); (5, "dim tomato") ]);
    ("dim teal", [(5, "pale beige"); (2, "faded blue"); (5, "dotted tan"); (5, "vibrant tomato") ]);
    ("bright red", [(4, "drab lavender"); (1, "dark purple"); (2, "wavy violet") ]);
    ("dotted teal", [(5, "dull crimson") ]);
    ("faded gray", [(4, "mirrored red") ]);
    ("pale purple", [(3, "faded gray"); (1, "clear gold"); (4, "clear cyan") ]);
    ("striped crimson", [(4, "dim aqua"); (3, "pale magenta"); (1, "drab white"); (1, "vibrant purple") ]);
    ("mirrored purple", [(3, "muted gray") ]);
    ("muted maroon", [(3, "plaid crimson"); (4, "posh aqua") ]);
    ("muted gold", [(3, "pale fuchsia"); (2, "dotted teal"); (3, "dotted chartreuse"); (4, "vibrant lime") ]);
    ("wavy silver", [(2, "plaid beige"); (3, "dull aqua"); (2, "pale lavender") ]);
    ("dim aqua", [(5, "bright beige") ]);
    ("dark tan", [(4, "pale gold") ]);
    ("light yellow", [(4, "dotted gray"); (5, "pale teal") ]);
    ("bright blue", [(3, "shiny coral"); (4, "striped salmon") ]);
    ("striped cyan", [(5, "light turquoise") ]);
    ("light gray", [(4, "vibrant teal"); (1, "shiny turquoise"); (1, "wavy olive"); (5, "dim white") ]);
    ("light cyan", [(3, "dark gray"); (5, "clear lavender"); (4, "dark beige") ]);
    ("light blue", [(5, "dim black"); (4, "drab tomato"); (2, "dim turquoise") ]);
    ("dull crimson", [(3, "pale silver"); (2, "faded beige") ]);
    ("dotted beige", [(2, "dotted aqua") ]);
    ("shiny olive", [(4, "bright plum"); (4, "clear plum"); (2, "wavy green"); (5, "faded tomato") ]);
    ("striped turquoise", [(1, "drab black") ]);
    ("pale chartreuse", [(5, "dotted brown") ]);
    ("mirrored turquoise", [(4, "shiny gold"); (3, "dark chartreuse") ]);
    ("posh beige", [(3, "dotted tan") ]);
    ("drab gray", [(3, "vibrant aqua") ]);
    ("shiny silver", [(4, "plaid gold"); (5, "shiny green") ]);
    ("bright crimson", [(5, "faded yellow"); (4, "bright plum"); (4, "mirrored gold") ]);
    ("dim yellow", [(2, "plaid lime"); (5, "bright salmon"); (4, "mirrored bronze") ]);
    ("dark crimson", [(4, "dull blue"); (2, "light olive"); (4, "mirrored green") ]);
    ("faded aqua", [(1, "dotted chartreuse"); (1, "muted orange") ]);
    ("pale turquoise", [(4, "dull silver") ]);
    ("clear orange", [(1, "pale gray"); (5, "striped bronze"); (5, "dim aqua") ]);
    ("mirrored red", [(1, "muted purple") ]);
    ("drab silver", []);
    ("faded silver", [(5, "mirrored turquoise"); (4, "striped purple") ]);
    ("wavy fuchsia", [(2, "faded purple"); (1, "wavy cyan"); (2, "muted cyan") ]);
    ("clear black", [(4, "drab turquoise"); (1, "plaid lime") ]);
    ("dim olive", [(5, "bright chartreuse"); (3, "striped silver") ]);
    ("mirrored tan", [(2, "striped indigo"); (3, "wavy gray"); (3, "clear tan") ]);
    ("mirrored yellow", [(2, "plaid plum"); (3, "striped salmon"); (4, "dim maroon") ]);
    ("shiny salmon", [(5, "dotted plum"); (5, "pale crimson") ]);
    ("dotted crimson", [(3, "dull yellow") ]);
    ("shiny fuchsia", [(5, "plaid lime") ]);
    ("drab turquoise", [(2, "dull crimson") ]);
    ("mirrored cyan", [(3, "posh green"); (5, "striped olive"); (5, "vibrant red") ]);
    ("faded crimson", [(3, "muted silver"); (4, "shiny olive") ]);
    ("light magenta", [(3, "posh crimson"); (5, "pale purple") ]);
    ("faded violet", [(3, "vibrant lime"); (1, "dim magenta"); (1, "dull lime") ]);
    ("dotted black", [(2, "light gold"); (2, "dim bronze"); (4, "wavy turquoise") ]);
    ("bright beige", [(4, "vibrant orange"); (4, "dark chartreuse"); (1, "muted gray"); (2, "bright tomato") ]);
    ("striped green", [(3, "pale beige"); (1, "pale brown"); (2, "posh brown"); (5, "striped olive") ]);
    ("dotted red", [(4, "vibrant orange"); (2, "pale gold") ]);
    ("plaid fuchsia", [(5, "pale teal"); (5, "pale fuchsia"); (4, "faded gray") ]);
    ("light beige", [(1, "muted red"); (5, "dotted purple"); (3, "striped salmon") ]);
    ("dim chartreuse", [(5, "muted maroon"); (4, "wavy maroon") ]);
    ("clear chartreuse", [(3, "striped lavender"); (2, "clear blue") ]);
    ("pale silver", [(2, "dark teal") ]);
    ("faded olive", [(4, "dotted turquoise"); (4, "drab indigo"); (5, "drab violet"); (3, "shiny blue") ]);
    ("clear blue", [(1, "muted black") ]);
    ("dull tan", [(5, "clear crimson"); (3, "dim tomato") ]);
    ("dark cyan", [(4, "wavy magenta"); (5, "vibrant olive"); (2, "posh gray"); (5, "dull magenta") ]);
    ("dotted white", [(1, "bright magenta"); (3, "pale red") ]);
    ("muted teal", [(5, "posh fuchsia"); (4, "drab turquoise"); (4, "posh red") ]);
    ("mirrored coral", [(1, "faded purple"); (2, "bright magenta"); (5, "dark yellow"); (3, "light plum") ]);
    ("dull orange", [(4, "dotted blue"); (5, "clear gray"); (3, "vibrant red") ]);
    ("bright aqua", [(4, "muted lime"); (2, "wavy plum"); (1, "shiny olive") ]);
    ("light maroon", [(1, "shiny gold"); (4, "light beige"); (1, "drab black") ]);
    ("dim green", [(4, "dull brown") ]);
    ("striped black", [(4, "dotted crimson") ]);
    ("mirrored bronze", [(4, "mirrored chartreuse"); (3, "dull lime"); (3, "wavy turquoise") ]);
    ("striped aqua", [(4, "dark gray"); (5, "faded beige"); (2, "dull lime") ]);
    ("shiny coral", [(5, "mirrored white"); (5, "shiny blue") ]);
    ("striped orange", [(4, "pale silver"); (4, "pale olive"); (4, "shiny olive"); (2, "bright chartreuse") ]);
    ("vibrant crimson", [(5, "shiny olive"); (5, "striped violet"); (2, "posh beige") ]);
    ("dotted chartreuse", [(5, "bright turquoise"); (5, "bright magenta") ]);
    ("vibrant purple", [(4, "posh violet") ]);
    ("vibrant violet", [(5, "posh aqua"); (4, "mirrored white"); (4, "dotted tan"); (4, "mirrored purple") ]);
    ("dotted violet", [(3, "bright brown"); (3, "pale yellow"); (4, "light gray"); (5, "dark green") ]);
    ("muted black", [(2, "light violet"); (5, "muted bronze") ]);
    ("mirrored orange", [(1, "plaid magenta"); (5, "muted red"); (3, "pale lime") ]);
    ("faded magenta", [(3, "striped cyan"); (4, "muted silver") ]);
    ("clear gray", [(4, "muted gray"); (2, "wavy turquoise"); (3, "dotted plum") ]);
];;

let solve (graph_input : (string * (int * string) list) list) target =
    let out_str output str =
        BatInnerIO.nwrite output str in

    let make_graph input =
        let do_row graph (outer, inner_lst) =
            let add_element graph (count, inner) =
                printf "add_element: %d %s\n" count inner;
                BatMultiPMap.add outer (count, inner) graph in
            printf "do_row: %s\n" outer;
            List.fold_left add_element graph inner_lst in

        List.fold_left do_row BatMultiPMap.empty input in

    let rec count_subtree start graph indent =
        let count_children lst =
            let do_child (count, child) ret =
                printf "%s do_child: %d, %s\n" indent count child;
                let child_count = count * (count_subtree child graph (indent ^ "    ")) in
                printf "%s child result = %d\n" indent child_count;
                ret + child_count in

            printf "%s add children: %s\n" indent start;
            let ret = BatSet.PSet.fold do_child lst 0 in
            printf "%s children result = %d\n" indent ret;
            ret in


        let children = BatMultiPMap.find start graph in
        1 + count_children children in

    let graph = make_graph graph_input in
    (count_subtree target graph "") - 1
;;

printf "result: %d\n" (solve input "shiny gold");;
